### ISSUE TITLE
Code Coverage Badge Is Broken

### ISSUE THREAD

**Issue by DuaneOBrien** [indeedeng/react-link-to-inbox#10]
This repo has a Code Coverage badge in the Readme.md that is currently broken. We should update the Readme to fix the broken badge.

**Comment by rbstrachan** [comment]
Hello @DuaneOBrien,

**Before I say anything, I want to point out that I don't fully understand how codecov.io works, so what I'm about to say might be completely wrong. If that's the case, please let me know and I'll delete this comment.**

---

I've double checked the badge url and it is correct, assuming the codecov repo is not private.

If the repo is private, the badge is most likely broken due to a missing access token for the codecov repo. If so, this can only be fixed by someone with access to the [codecov.io](https://codecov.io) account.

To fix the badge, either the repo must be made public or an api access token generated and appended to the badge url, replacing `#` below with the token;

`https://img.shields.io/codecov/c/github/indeedeng/react-link-to-inbox.svg?token=#`

You can generate an access token by going to Account > Access > Create > Generate.

---

If I am wrong and none of that made sense, I'm out of ideas - sorry.

Hope this helps.

**Comment by hnarasaki** [comment]
Is this issue still open?
